//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRD_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserLogin
    {
        public long UserId { get; set; }
        public Nullable<long> RoleId { get; set; }
        public Nullable<long> KitchenSectionId { get; set; }
        public string EmailId { get; set; }
        public string restroId { get; set; }
        public string UserName { get; set; }
        public string AccessCode { get; set; }
        public string AccessKey { get; set; }
        public string Password { get; set; }
        public Nullable<long> EmpId { get; set; }
        public string PasswordKey { get; set; }
        public string UserPin { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsLogIn { get; set; }
        public Nullable<bool> IsLoginFirstTime { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LastLogout { get; set; }
        public string Accessdate { get; set; }
    }
}
